// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9iWhQES18DBgc5zQsC3oKmS6PdIHxR4',
    appId: '1:824331704475:web:98225961e89fcfb4598e3e',
    messagingSenderId: '824331704475',
    projectId: 'homeloan-9da47',
    authDomain: 'homeloan-9da47.firebaseapp.com',
    storageBucket: 'homeloan-9da47.appspot.com',
    measurementId: 'G-BB5H9FXWZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQWalRTSCrHkByFCsf4xcZ9aTf6T3sqrE',
    appId: '1:824331704475:android:5034d52c05798d63598e3e',
    messagingSenderId: '824331704475',
    projectId: 'homeloan-9da47',
    storageBucket: 'homeloan-9da47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3wGN9BxDKGZp-AYk2WElFnRejNvWGhU',
    appId: '1:824331704475:ios:094af517bc261f1e598e3e',
    messagingSenderId: '824331704475',
    projectId: 'homeloan-9da47',
    storageBucket: 'homeloan-9da47.appspot.com',
    iosBundleId: 'com.example.loan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH3wGN9BxDKGZp-AYk2WElFnRejNvWGhU',
    appId: '1:824331704475:ios:094af517bc261f1e598e3e',
    messagingSenderId: '824331704475',
    projectId: 'homeloan-9da47',
    storageBucket: 'homeloan-9da47.appspot.com',
    iosBundleId: 'com.example.loan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm9iWhQES18DBgc5zQsC3oKmS6PdIHxR4',
    appId: '1:824331704475:web:f228d7e4ec1ac7b7598e3e',
    messagingSenderId: '824331704475',
    projectId: 'homeloan-9da47',
    authDomain: 'homeloan-9da47.firebaseapp.com',
    storageBucket: 'homeloan-9da47.appspot.com',
    measurementId: 'G-M3FT998FZP',
  );
}
